local commands = {
  {
    title = "Change colorscheme",
    desc = "Pick from the available color schemes.",
    mode = "n",
    keywords = "pick theme",
    alias = "Telescope colorscheme",
  },
  {
    title = "Explore Vim Options",
    desc = "Explore vim options and view or modify their current values.",
    mode = "n",
    alias = "Telescope vim_options",
    keywords = "settings",
  },
  {
    title = "Find Buffers",
    desc = "Search for currently open buffers.",
    mode = "n",
    alias = "Telescope buffers",
  },
  {
    title = "Find Files",
    desc = "Search for files in the current working directory.",
    mode = "n",
    keywords = "search",
    alias = "Telescope find_files",
  },
  {
    title = "Find Recent Files",
    desc = "Search for previously open files.",
    mode = "n",
    keywords = "search",
    alias = "Telescope oldfiles",
  },
  {
    title = "Find Repository Files",
    desc = "Search for files in the current git repository.",
    mode = "n",
    keywords = "git",
    alias = "Telescope git_files",
  },
  {
    title = "View Git Commits",
    desc = "List git commits.",
    mode = "n",
    keywords = "history",
    alias = "Telescope git_commits",
  },
  {
    title = "View File History",
    desc = "List git commits for the current file.",
    mode = "n",
    keywords = "git commits",
    alias = "Telescope git_bcommits",
  },
  {
    title = "View Git Branches",
    desc = "List git branches for the current repostory.",
    mode = "n",
    keywords = "checkout",
    alias = "Telescope git_branches",
  },
  {
    title = "View Git Status",
    desc = "View the current changes in each file.",
    mode = "n",
    alias = "Telescope git_status",
  },
  {
    title = "View Git Stash",
    desc = "View the currently stashed items in git.",
    mode = "n",
    alias = "Telescope git_stash",
  },
  {
    title = "Resume Search",
    desc = "Resume the previous search.",
    mode = "n",
    keywords = "back find",
    alias = "Telescope resume",
  },
  {
    title = "Search Definitions",
    desc = "Search variable names and functions in the current file.",
    mode = "n",
    keywords = "variables functions names definitions",
    alias = "Telescope treesitter",
  },
  {
    title = "Search Commands",
    desc = "Search all of the currently available commands.",
    mode = "n",
    alias = "Telescope commands",
  },
  {
    title = "Search Command History",
    desc = "Search commands that were executed recently.",
    mode = "n",
    alias = "Telescope command_history",
  },
  {
    title = "Search in Current File",
    desc = "Fuzzily search for a string in the current file.",
    mode = "n",
    alias = "Telescope current_buffer_fuzzy_find",
  },
  {
    title = "Search in Files",
    desc = "Search for a string in the current working directory.",
    mode = "n",
    keywords = "find grep",
    alias = "Telescope live_grep",
  },
  {
    title = "Search for Current Word",
    desc = "Searches for the string under the cursor in the current working directory.",
    mode = "n",
    keywords = "files find grep word",
    alias = "Telescope grep_string",
  },
  {
    title = "Search Help Tags",
    desc = "Lists available help tags and opens a new window with the relevant help info.",
    mode = "n",
    alias = "Telescope help_tags",
  },
  {
    title = "Search Keymappings",
    desc = "Search all of the current keymappings.",
    mode = "n",
    keywords = "find key mapping keymap",
    alias = "Telescope keymaps",
  },
  {
    title = "Search Quickfix List",
    desc = "Search items in the quickfix list.",
    mode = "n",
    alias = "Telescope quickfix",
  },
  {
    title = "Open Telescope",
    desc = "View a list of available fuzzy finders.",
    mode = "n",
    alias = "Telescope search tool",
  },
}

return commands
